from dataclasses import dataclass
from typing import Tuple

# ============================================================
# CRC-4 engine for ASPEP header generated by ChatGPT
#   - CRC over lower 28 bits
#   - CRC inserted into upper 4 bits [31:28]
#   - CRC-4 from CCITT-G.704 (X^4 + X + 1)
# ============================================================

@dataclass
class Crc4Config:
	# x^4 + x + 1 -> poly = 0x3
	poly: int = 0x3
	init: int = 0x0
	xorout: int = 0x0
	pass

class AspepCrc4:
	def __init__( self, config: Crc4Config = Crc4Config() ):
		self.cfg = config
		pass

	def computeCrc( self, header28: int ) -> int:
		header28 &= 0x0FFFFFFF
		crc = ( self.cfg.init & 0xF )

		crc = self.__updateByte( crc, ( header28 >> 0 ) & 0xFF )
		crc = self.__updateByte( crc, ( header28 >> 8 ) & 0xFF )
		crc = self.__updateByte( crc, ( header28 >> 16 ) & 0xFF )
		crc = self.__updateNibble( crc, ( header28 >> 24 ) & 0x0F )

		crc ^= self.cfg.xorout
		return ( crc & 0xF )

	def packHeader( self, header28: int ) -> int:
		header28 &= 0x0FFFFFFF
		crc = self.computeCrc( header28 )
		return ( header28 | ( crc << 28 ) )

	def verifyHeader( self, header32: int ) -> bool:
		received_crc = ( header32 >> 28 ) & 0xF
		payload28 = ( header32 & 0x0FFFFFFF )
		computed_crc = self.computeCrc( payload28 )
		return ( received_crc == computed_crc )
    
	def __updateNibble( self, crc: int, nibble: int ) -> int:
		crc &= 0xF
		nibble &= 0xF
		crc ^= nibble

		for _ in range( 4 ):
			if crc & 0x8:
				crc = ( ( crc << 1 ) & 0xF ) ^ self.cfg.poly
			else:
				crc = ( crc << 1 ) & 0xF
		return ( crc & 0xF )

	def __updateByte( self, crc: int, byte: int ) -> int:
		# low nibble first
		crc = self.__updateNibble( crc, byte & 0x0F )
		crc = self.__updateNibble( crc, ( byte >> 4 ) & 0x0F )
		return ( crc & 0xF )

 # ============================================================
# CRC-16 engine for ASPEP header generated by ChatGPT
#   - CRC over payload bytes
#   - CRC-16 from CCITT-X.25 standard (x^16 + x^12 + x^5 + 1)
# ============================================================

@dataclass
class Crc16Config:
	# x^16 + x^12 + x^5 + 1 -> poly = 0x8408
	poly: int = 0x8408
	init: int = 0x0000
	xorout: int = 0xFFFF
	pass

class AspepCrc16:
	def __init__( self, config: Crc16Config = Crc16Config() ):
		self.cfg = config
		pass
     
	def computeCrc( self, payload: bytes ) -> int:
		crc = self.cfg.init
		for b in payload:
			crc ^= b
			for _ in range( 8 ):
				if crc & 0x0001:
					crc = ( crc >> 1 ) ^ self.cfg.poly
				else:
					crc >>= 1
				crc &= 0xFFFF
		crc ^= self.cfg.xorout
		return crc